version: '3.8'

services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    restart: unless-stopped

  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_APPLICATION_NAME=config-service
    restart: unless-stopped
    depends_on:
      - discovery-service

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - discovery-service
      - config-service
    restart: unless-stopped

  keynote-service:
    build:
      context: ./keynote-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - discovery-service
      - config-service
    restart: unless-stopped

  conference-service:
    build:
      context: ./conference-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - discovery-service
      - config-service
    restart: unless-stopped

